name: Native Gems
concurrency:
  group: "${{github.workflow}}-${{github.ref}}"
  cancel-in-progress: true
on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v*.*.*
  pull_request:
    types: [opened, synchronize]
    branches:
      - '*'

jobs:
  package:
    strategy:
      fail-fast: false
      matrix:
        platform: ["ruby", "x64-mingw32", "x64-mingw-ucrt", "x86_64-darwin", "x86_64-linux"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rm Gemfile.lock
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
          bundler: latest
          bundler-cache: true
      - run: "bundle exec rake gem:${{matrix.platform}}"
      - uses: actions/upload-artifact@v2
        with:
          name: gem-${{matrix.platform}}
          path: pkg
          retention-days: 1

  vanilla-install:
    needs: ["package"]
    runs-on: ubuntu-latest
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
      - uses: actions/download-artifact@v2
        with:
          name: gem-ruby
          path: pkg
      - run: "gem install pkg/tailwindcss-rails-*.gem"
      - run: "tailwindcss 2>&1 | fgrep 'ERROR: Cannot find the tailwindcss executable'"

  linux-install:
    needs: ["package"]
    runs-on: ubuntu-latest
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
      - uses: actions/download-artifact@v2
        with:
          name: gem-x86_64-linux
          path: pkg
      - run: "gem install pkg/tailwindcss-rails-*.gem"
      - run: "tailwindcss --help"

  linux-musl-install:
    needs: ["package"]
    runs-on: ubuntu-latest
    container:
      image: ruby:3.1-alpine
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: gem-x86_64-linux
          path: pkg
      - run: "gem update --system"
      - run: "apk add build-base" # TODO: remove after https://github.com/rubygems/rubygems/issues/5914 is in a rubygems release
      - run: "gem install pkg/tailwindcss-rails-*.gem"
      - run: "tailwindcss --help"

  darwin-install:
    needs: ["package"]
    runs-on: macos-latest
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
      - uses: actions/download-artifact@v2
        with:
          name: gem-x86_64-darwin
          path: pkg
      - run: "gem install pkg/tailwindcss-rails-*.gem"
      - run: "tailwindcss --help"

  windows-install:
    needs: ["package"]
    runs-on: windows-latest
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
      - uses: actions/download-artifact@v2
        with:
          name: gem-x64-mingw32
          path: pkg
      - run: "gem install pkg/tailwindcss-rails-*.gem"
      - run: "tailwindcss --help"

  windows-ucrt-install:
    needs: ["package"]
    runs-on: windows-2022
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
      - uses: actions/download-artifact@v2
        with:
          name: gem-x64-mingw-ucrt
          path: pkg
      - run: "gem install pkg/tailwindcss-rails-*.gem"
      - run: "tailwindcss --help"
